In [1]:
import pandas as pd
import numpy as np


# Read the CSV and Perform Basic Data Cleaning


In [2]:
df = pd.read_csv("Resources/data.csv")

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
# # Remove Space for `FALSE POSITIVE` category
# mask = df["koi_disposition"] == "FALSE POSITIVE"
# df.loc[mask, "koi_disposition"] = "False_Positive"
# df["koi_disposition"]

# Create a Train Test Split

Use `diagnosis` for the y values

In [4]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]
print(X.shape, y.shape)

(569, 31) (569,)


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)



X_train.head()

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
251  88518501        11.50         18.45           73.28      407.4   
373    901288        20.64         17.35          134.80     1335.0   
211   8810528        11.84         18.94           75.51      428.0   
52     857374        11.94         18.24           75.71      437.6   
315    894089        12.49         16.85           79.19      481.6   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
251          0.09345           0.05991        0.026380             0.020690   
373          0.09446           0.10760        0.152700             0.089410   
211          0.08871           0.06900        0.026690             0.013930   
52           0.08261           0.04751        0.019720             0.013490   
315          0.08511           0.03834        0.004473             0.006423   

     symmetry_mean           ...             radius_worst  texture_worst  \
251         0.1834           ...                    12.97          22.46   
373         0.1571           ...                    25.37          23.17   
211         0.1533           ...                    13.30          24.99   
52          0.1868           ...                    13.10          21.33   
315         0.1215           ...                    13.34          19.71   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
251            83.12       508.9            0.1183            0.10490   
373           166.80      1946.0            0.1562            0.30550   
211            85.22       546.3            0.1280            0.18800   
52             83.67       527.2            0.1144            0.08906   
315            84.48       544.2            0.1104            0.04953   

     concavity_worst  concave points_worst  symmetry_worst  \
251          0.08105               0.06544          0.2740   
373          0.41590               0.21120          0.2689   
211          0.14710               0.06913          0.2535   
52           0.09203               0.06296          0.2785   
315          0.01938               0.02784          0.1917   

     fractal_dimension_worst  
251                  0.06487  
373                  0.07055  
211                  0.07993  
52                   0.07408  
315                  0.06174  

[5 rows x 31 columns]

# Pre-processing

Scale the data using the MinMaxScaler

In [6]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)



X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



/anaconda3/envs/PythonWebMongo/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [7]:
X_train_scaled



array([[0.09712354, 0.21387666, 0.29556983, ..., 0.22487973, 0.23161837,
        0.06447593],
       [0.00097949, 0.64645748, 0.25836997, ..., 0.7257732 , 0.22156515,
        0.1017316 ],
       [0.00965845, 0.22996829, 0.31214068, ..., 0.23756014, 0.19120836,
        0.16325594],
       ...,
       [0.00998991, 0.28486914, 0.52147447, ..., 0.20347079, 0.14606742,
        0.0516201 ],
       [0.00099086, 0.34166312, 0.3659114 , ..., 0.46013746, 0.19101124,
        0.15440115],
       [0.00096441, 0.63083913, 0.58674332, ..., 0.58316151, 0.31263552,
        0.16364948]])

# Train the Deep Learning Model



## Mac Users

In [8]:
import tensorflow as tf
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense

Using TensorFlow backend.


## Windows Users

In [9]:
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.utils import to_categorical
# from tensorflow.keras.layers import Dense

In [10]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)


In [11]:
encoded_y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,

In [12]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [13]:
# from sklearn.svm import SVC 
# model = SVC(kernel='linear')
# model.fit(X_train_scaled, y_train)

In [14]:
y_train_categorical

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [15]:
y_train_categorical.shape

(426, 2)

In [16]:
model = Sequential()
model.add(Dense(units=40, activation='relu', input_dim=31))
model.add(Dense(units=40, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [17]:
# Compile and fit the model
model.compile(optimizer='adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 40)                1280      
_________________________________________________________________
dense_2 (Dense)              (None, 40)                1640      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 82        
Total params: 3,002
Trainable params: 3,002
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2)

Epoch 1/60
 - 0s - loss: 0.6783 - acc: 0.6127
Epoch 2/60
 - 0s - loss: 0.5989 - acc: 0.8709
Epoch 3/60
 - 0s - loss: 0.5211 - acc: 0.8991
Epoch 4/60
 - 0s - loss: 0.4358 - acc: 0.8967
Epoch 5/60
 - 0s - loss: 0.3545 - acc: 0.9014
Epoch 6/60
 - 0s - loss: 0.2869 - acc: 0.9131
Epoch 7/60
 - 0s - loss: 0.2418 - acc: 0.9319
Epoch 8/60
 - 0s - loss: 0.2104 - acc: 0.9249
Epoch 9/60
 - 0s - loss: 0.1987 - acc: 0.9202
Epoch 10/60
 - 0s - loss: 0.1717 - acc: 0.9366
Epoch 11/60
 - 0s - loss: 0.1589 - acc: 0.9484
Epoch 12/60
 - 0s - loss: 0.1476 - acc: 0.9460
Epoch 13/60
 - 0s - loss: 0.1376 - acc: 0.9577
Epoch 14/60
 - 0s - loss: 0.1278 - acc: 0.9601
Epoch 15/60
 - 0s - loss: 0.1190 - acc: 0.9648
Epoch 16/60
 - 0s - loss: 0.1117 - acc: 0.9671
Epoch 17/60
 - 0s - loss: 0.1053 - acc: 0.9671
Epoch 18/60
 - 0s - loss: 0.0974 - acc: 0.9718
Epoch 19/60
 - 0s - loss: 0.0924 - acc: 0.9671
Epoch 20/60
 - 0s - loss: 0.0910 - acc: 0.9812
Epoch 21/60
 - 0s - loss: 0.0828 - acc: 0.9836
Epoch 22/60
 - 0s - lo

In [20]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}") 
    


Normal Neural Network - Loss: 0.09770885237551236, Accuracy: 0.9790209790209791


In [21]:
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Deep Neural Network - Loss: 0.09770885237551236, Accuracy: 0.9790209790209791


In [28]:
encoded_predictions = model.predict_classes(X_test_scaled)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [29]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test)}")

Predicted classes: ['M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B'
 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'M'
 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M'
 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'B']
Actual Labels: ['M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',

In [30]:
df=pd.DataFrame({"Prediction": prediction_labels, "Actual": y_test}).reset_index(drop=True)

In [31]:
df.head()

Prediction Actual
0          M      M
1          B      B
2          M      M
3          B      B
4          B      B

In [32]:
df.to_csv("DLVisual.csv", sep='\t', encoding='utf-8')